export const TOOLS = [
  {
    id: 1,
    name: 'Access',
    botName: 'access_app_bot',
    description: 'Access to chats and channels',
    link: 'https://t.me/access_app_bot?startapp=',
    github: 'https://github.com/OpenBuilders/gateway-tool',
    contributors: [
      {
        name: '@takoy_sasha',
        link: null,
        image: 'https://t.me/i/userpic/320/takoy_sasha.jpg',
        role: 'The Visionary',
      },
      {
        name: '@kirill_sidorets',
        link: 'https://t.me/kirill_sidorets',
        image: 'https://t.me/i/userpic/320/kirill_sidorets.jpg',
        role: 'Designer',
      },
      {
        name: '@danoctua',
        link: 'https://github.com/danoctua',
        image: 'https://t.me/i/userpic/320/danoctua.jpg',
        role: 'Developer',
      },
      {
        name: '@mityai_shamal',
        link: 'https://github.com/Exerbaind',
        image: 'https://t.me/i/userpic/320/mityai_shamal.jpg',
        role: 'Developer',
      },
    ],
    isActive: true,
    icon: 'gatewayBot',
    extraLinks: [
      {
        name: 'Feedback or Suggestion',
        link: 'https://t.me/tools_community',
      },
      {
        name: 'How to Contribute?',
        link: 'https://github.com/OpenBuilders/gateway-tool?tab=readme-ov-file#contributing',
      },
    ],
  },
  {
    id: 2,
    name: 'Giveaway',
    description: 'Create and join giveaways',
    link: null,
    isActive: false,
    icon: 'giveawayBot',
    extraLinks: null,
    contributors: null,
    github: null,
    botName: null,
  },
  {
    id: 3,
    name: 'Vesting',
    description: 'Scheduled token releases',
    link: null,
    isActive: false,
    icon: 'vestingBot',
    extraLinks: null,
    contributors: null,
    github: null,
    botName: null,
  },
];
