export const TOOLS = [
  {
    id: 1,
    name: 'Access',
    botName: 'access_app_bot',
    description: 'Access to chats and channels',
    link: 'https://t.me/access_app_bot?startapp=',
    github: 'https://github.com/OpenBuilders/access-tool',
    contributors: [
      {
        name: '@danoctua',
        link: 'https://github.com/danoctua',
        image: 'https://t.me/i/userpic/320/danoctua.jpg',
        role: 'Developer',
      },
      {
        name: '@kirill_sidorets',
        link: null,
        image: 'https://t.me/i/userpic/320/kirill_sidorets.jpg',
        role: 'Designer',
      },
      {
        name: '@mityai_shamal',
        link: 'https://github.com/Exerbaind',
        image: 'https://t.me/i/userpic/320/mityai_shamal.jpg',
        role: 'Developer',
      },
    ],
    isActive: true,
    icon: null,
    image: 'https://t.me/i/userpic/320/access_app_bot.jpg',
    extraLinks: [
      {
        name: 'Feedback or Suggestion',
        link: 'https://t.me/c/tools_community/192942',
      },
      {
        name: 'How to Contribute?',
        link: 'https://github.com/OpenBuilders/access-tool?tab=readme-ov-file#contributing',
      },
    ],
  },
  {
    id: 2,
    name: 'Contests',
    botName: 'contests_app_bot',
    description: 'Manage and join contests effortlessly!',
    link: 'https://t.me/contests_app_bot?startapp=',
    github: 'https://github.com/OpenBuilders/contest-tool',
    contributors: [
      {
        name: '@Eyfan',
        link: 'https://github.com/erfanmola',
        image: 'https://t.me/i/userpic/320/Eyfan.jpg',
        role: 'Developer',
      },
    ],
    isActive: true,
    icon: null,
    image: 'https://t.me/i/userpic/320/contests_app_bot.jpg',
    extraLinks: [
      {
        name: 'Feedback or Suggestion',
        link: 'https://t.me/c/tools_community/193226',
      },
      {
        name: 'How to Contribute?',
        link: 'https://docs.contest.tools.tg/',
      },
    ],
  },
  {
    id: 3,
    name: 'Giveaway',
    description: 'Create and join giveaways',
    link: null,
    isActive: false,
    icon: 'giveawayBot',
    extraLinks: null,
    contributors: null,
    github: null,
    botName: null,
  },
  {
    id: 4,
    name: 'Vesting',
    description: 'Scheduled token releases',
    link: null,
    isActive: false,
    icon: 'vestingBot',
    extraLinks: null,
    contributors: null,
    github: null,
    botName: null,
  },
];
